<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Models\" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="Avalonia.Base">
        <HintPath>..\Views\bin\Debug\net10.0\Avalonia.Base.dll</HintPath>
      </Reference>
    </ItemGroup>

</Project>
